language: objective-c
osx_image: xcode11.5
xcode_project: SmartDeviceLink-iOS.xcodeproj
xcode_scheme:
    - SmartDeviceLink
    - SmartDeviceLink-Example-ObjC
    - SmartDeviceLink-Example-Swift
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
xcode_sdk:
    - iphonesimulator13.5
env:
  global:
    - FRAMEWORK_NAME=SmartDeviceLink

cache:
  directories:
  - Carthage

notifications:
  email: false

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

script:
- set -o pipefail && xcodebuild -configuration Debug ONLY_ACTIVE_ARCH=NO RUN_CLANG_STATIC_ANALYZER=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES ENABLE_TESTABILITY=YES test;

after_success:
- bash <(curl -s https://codecov.io/bash) -J 'SmartDeviceLink'
