language: objective-c
osx_image: xcode11.5
xcode_project: SmartDeviceLink-iOS.xcodeproj
xcode_scheme:
    - SmartDeviceLinkTests
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
xcode_sdk:
    - iphonesimulator13.5
env:
  global:
    - FRAMEWORK_NAME=SmartDeviceLink

cache:
  directories:
  - Carthage

notifications:
  email: false

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

after_success:
- bash <(curl -s https://codecov.io/bash) -J 'SmartDeviceLink'
